server:
  port: 8000

eureka:
  instance:
    hostname: localhost # 主机名
    prefer-ip-address: true # 是否将自己的ip注册到eureka中，默认false 注册 主机名
    ip-address: 127.0.0.1  # 设置当前实例ip
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}   # 修改instance-id显示
    lease-renewal-interval-in-seconds: 3 # 每一次eureka client 向 eureka server发送心跳的时间间隔
    lease-expiration-duration-in-seconds: 9 # 如果9秒内eureka server没有收到eureka client的心跳包，则剔除该服务
  client:
    service-url:
      defaultZone: http://eureka-server1:8761/eureka,http://eureka-server2:8762/eureka # eureka服务端地址，将来客户端使用该地址和eureka进行通信
    register-with-eureka: true # 是否将自己的路径 注册到eureka上。
    fetch-registry: true # 是否需要从eureka中抓取数据。

spring:
  application:
    name: eureka-provider # 设置当前应用的名称。将来会在eureka中Application显示。将来需要使用该名称来获取路径
